# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run resume.py to generate a resume file
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python3 resume.py --no-pdf
    - name: Archive the generated resume
      uses: actions/upload-artifact@v4
      with:
        name: kaya_resume
        path: output/test/code-coverage.html
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: kaya_resume
        path: resume.html
        retention-days: 30
